openapi: "3.0.2"
info:
  title: MazeDemoApi
  version: "1.0"
servers:
  - url: http://localhost:8080/
paths:
  /mazes:
    get:
      responses:
        '200':
          description: 全迷路情報取得
          content:
            application/json:
              schema:
                allOf:
                  - type: array
                    items:
                      properties:
                        id:
                          type: string
                          format: uuid
                          example: "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
                      $ref: "#/components/schemas/maze"
    post:
      tags:
        - create
      summary: 迷路登録
      description: クライアントが入力する情報をもとに迷路情報を登録する
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/maze"
      responses:
        '201':
          description: 迷路登録成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/maze"

  /mazes/{id}:
    get:
      responses:
        '200':
          description: 迷路情報取得(ID)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/getMaze"


components:
  schemas:
    maze:
      type: object
      properties:
        title:
          type: string
          example: 迷路1
        level:
          type: integer
          example: 0
        status:
          type: string
          enum:
            - DRAFT
            - PUBLISHED
            - PRIVATE
      required:
        - title
        - level
        - status
    getMaze:
      allOf:
        - $ref: "#/components/schemas/maze"
        - type: object
          properties:
            id:
              type: string
              format: uuid
              example: "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
